
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-Articles-placeholder","number":87,"title":"Articles placeholder","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/87"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-Articles-table","number":86,"title":"Articles Table","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/86"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewTable","number":85,"title":"Create MenuItemReview Table","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/85"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-HelpRequest-Placeholder","number":84,"title":"Create HelpRequest Placeholder Pages","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/84"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-Articles-form","number":79,"title":"Articles Form component","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/79"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-RecRequest-component","number":78,"title":"Recommendation Request Form Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/78"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"al-menuitem-index","number":77,"title":"Menu Item Index and Edit","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/77"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-RecRequest-fixtures","number":76,"title":"Created Recommendation Request Fixtures ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/76"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"al-menuitem-create","number":69,"title":"Menu Item Create","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/69"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"al-menuitem-placeholders","number":68,"title":"Menu Item placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/68"}]
