
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewEditPage","number":94,"title":"Add MenuItemReview Edit Page and Tests ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/94"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewIndexPage","number":93,"title":"Add MenuItemReview Index Page and Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/93"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewCreatePage","number":92,"title":"Add MenuItemReview Create and Test Pages","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/92"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewPlaceholder","number":91,"title":"Add MenuItemReview Pages Placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/91"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-Articles-edit","number":90,"title":"Articles Edit Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/90"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-Articles-index","number":89,"title":"Articles Index Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/89"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-Articles-create","number":88,"title":"Articles Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/88"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-Articles-placeholder","number":87,"title":"Articles placeholder","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/87"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewTable","number":85,"title":"Create MenuItemReview Table","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/85"}]
