
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-Organization","number":113,"title":"Created Edit Page for UCSBOrganization and tested","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/113"},{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-Organization-Index","number":110,"title":"Index Page for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/110"},{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-Organization-Create","number":109,"title":"Created Page for UCSBOrganization and tested","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/109"},{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-Organization-Copy","number":108,"title":"Copied Placeholders for UCSBOrganization pages and added to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/108"},{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-Organization-Table","number":107,"title":"Created and Tested Organization Table Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/107"},{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-Organization-Form-Fixed","number":104,"title":"Created and Tested Organization Form Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/104"}]
