
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-h05","number":120,"title":"Added Organization Integration Tests (h05)","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/120"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"jl-h05","number":119,"title":"Added RecRequest Integration (h05)","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/119"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-h05","number":118,"title":"Add HelpRequest Integration and End-to-end tests (h05)","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/118"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"al-h05-e2e","number":117,"title":"UCSB Dining Commons Menu Item New Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/117"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewTests","number":115,"title":"Add MenuItemReview Integration Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/115"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":"Ridhit Garg"},"headRefName":"Ridhit-h05","number":114,"title":"Ridhit - h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/114"}]
