
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewTests","number":115,"title":"Add MenuItemReview Integration Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/115"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":"Ridhit Garg"},"headRefName":"Ridhit-h05","number":114,"title":"Ridhit - h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-4/pull/114"}]
